file_server/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import settings

urlpatterns = [
    path("", include('server.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/urls.py
from django.contrib.auth import views as auth_view
from django.urls import path

from . import views

app_name = "server"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:file_id>/download/", views.download, name="download"),
    path("<int:file_id>/email/", views.create_email, name="create_email"),
    path("email/", views.send_email, name="send_email"),
    path("register/", views.register, name='register'),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout")
]

server/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField(unique=True)

    USERNAME_FIELD = "email"

    REQUIRED_FIELDS = ["username"]


class File(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    file = models.FileField()
    downloads = models.IntegerField(default=0)
    emails_sent = models.IntegerField(default=0)

server/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User, File
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


def validate_allowed_file(value):
    extension = value.name.split(".")[-1]
    allowed_extensions = ["pdf", "jpg", "jpeg", "png", "mp3", "mp4", "mkv"]
    if extension.lower() not in allowed_extensions:
        raise forms.ValidationError("Unsupported file type")


class FileAdminForm(forms.ModelForm):
    class Meta:
        model = File
        fields = "__all__"

    file = forms.FileField(validators=[validate_allowed_file])

server/views.py
import os

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.core.mail import EmailMessage
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.http import FileResponse
from django.template.loader import get_template

from .models import File

from .forms import CreateUserForm


@login_required
def index(request):
    if request.method == "POST":
        search = request.POST["search"]
        files = File.objects.filter(title__contains=search)
    else:
        files = File.objects.all()
    return render(request, "server/feed.html", {"files": files})


@login_required
def download(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    
    file_path = file.file.path

    file_name = os.path.basename(file_path)

    response = FileResponse(open(file_path, "rb"), content_type="application/octet-stream")
    response['Content-Disposition'] = f'attachment; filename="{file_name}"'

    file.downloads += 1
    file.save()

    return response


@login_required
def create_email(request, file_id):
    file = get_object_or_404(File, pk=file_id)
    # get message after email sent successfully
    message = request.GET.get("message", None)
    return render(request, "server/email.html", {"file": file, "message": message})

@login_required
def send_email(request):
    file_id = request.POST["id"]
    file_object = get_object_or_404(File, pk=file_id)

    subject = file_object.title
    message = file_object.description

    sender = request.user.email
    receiver = [request.POST["receiver"]]

    email = EmailMessage(subject, message, sender, receiver)
    email.content_subtype = "html"

    file = file_object.file

    email.attach_file(file.path)
    try:
        email.send()
        # increment emails_sent for the file model
        file_object.emails_sent += 1
        file_object.save()
        message = "File emailed successfully"
    except ConnectionRefusedError:
        message = "File emailing not configured to work in production. You can test locally with Mailhog"

    return redirect(f"{request.META['HTTP_REFERER']}?message={message}")


def send_confirmation_email(username, subject, to_email, data):
    from_email = "test@email.com"
    htmly = get_template("server/auth/confirmation_email.html")
    html_content = htmly.render(data)
    email = EmailMessage(subject, html_content, from_email, to_email)
    email.content_subtype = "html"
    try:
        email.send()
    except ConnectionRefusedError:
        pass    # production environment
        


def register(request):
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()

            # send confirmation email upon signup
            username = form.cleaned_data.get("username")
            email = [form.cleaned_data.get("email")]
            data = {
                "title": "Signup successful", 
                "message": f"Congratulations {username}. Your account has been created successfully"
            }

            send_confirmation_email(username, "account creation", email, data)

            return redirect("server:login")
    else:
        form = CreateUserForm()

    return render(request, "server/auth/signup.html", {"form": form})


def user_login(request):
    if request.method == "POST":
        email = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=email, password=password)
        if user:
            login(request, user)
            
            # send confirmation email after login
            username = user.username
            to_email = [email]

            data = {
                "title": "Account Login",
                "message": f"Hello {username}, Your account has been logged in recently. If it was not you, kindly reset your password"
            }

            send_confirmation_email(username, "account login", to_email, data)

            return redirect("server:index")
        
        message = "Email and password do not match any user. Please try again"
        form = AuthenticationForm(request.POST)
    else:
        message = ""
        form = AuthenticationForm()

    return render(request, "server/auth/login.html", {"message": message, "form": form})


def user_logout(request):
    logout(request)
    return redirect("server:login")

server/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>File Server</title>
  <link rel="stylesheet" href="{% static 'server/css/bootstrap.min.css' %}">
</head>
<body>

{% block content %}{% endblock %}

</body>
</html>

server/templates/server/email.html
{% extends "base.html" %}

{% block content %}

  <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'server:index' %}">File server</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'server:index' %}">Feed</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<div class="text-center mt-4"></div>
{% if message %}
<div class="d-flex justify-content-center">
  <div class="w-25 my-4 bg-success text-white p-4">{{ message }}</div>
</div>
{% endif %}
<div class="d-flex justify-content-center">
  <div class="card mb-3" style="max-width: 20rem;">
    <div class="card-header">Send email</div>
    <div class="card-body">
      <form method="post" action="{% url 'server:send_email' %}">
        {% csrf_token %}
        <fieldset>
          <div class="form-group">
            <label for="id" class="form-label mt-4">File</label>
            <select name="id"  id="id" class="form-control">
              <option value="{{ file.id }}">{{ file.title }}</option>
            </select>
          </div>
          <div class="form-group">
            <label for="receiver" class="form-label mt-4">Email address of receiver</label>
            <input type="email" class="form-control" id="receiver" name="receiver">
          </div>

          <button type="submit" class="btn btn-primary mt-4">Send</button>
        </fieldset>
      </form>
    </div>
  </div>
</div>

{% endblock %}

server/templates/server/feed.html
{% extends "base.html" %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'server:index' %}">File Server</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'server:logout' %}">Logout</a>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'server:index' %}" method="POST">
        {% csrf_token %}
        <input class="form-control me-sm-2" type="text" placeholder="Search by title" name="search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div class="text-center mt-4">
  <h3>All Files</h3>
</div>

<div class="mx-4">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
    {% for file in files %}
      <tr>
        <th scope="row">{{ file.id }}</th>
        <td>{{ file.title }}</td>
        <td>{{ file.description }}</td>
        <td>
          <div class="d-flex">
            <div class="mx-1"><a href="{{ file.file.url }}" target="_blank" class="btn btn-info">preview</a></div>
            <div class="mx-1"><a href="{% url 'server:create_email' file.id %}" class="btn btn-info">send as email</a></div>
            <div class="mx-1"><a href="{% url 'server:download' file.id %}" class="btn btn-info">download</a></div>
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}